In [1]:
import copy
import os
import argparse
import torch
import numpy as np
import random

%load_ext autoreload
%autoreload 2
from erasure.utils.config.local_ctx import Local
from erasure.utils.config.global_ctx import Global 
from erasure.core.factory_base import ConfigurableFactory
from erasure.data.datasets.DatasetManager import DatasetManager

In [2]:
config_file = os.path.join("configs", "survey", "IMDB.jsonc")
#config_file = os.path.join("configs", "example.jsonc")


global_ctx = Global(config_file)
global_ctx.factory = ConfigurableFactory(global_ctx)

#Create Dataset
data_manager = global_ctx.factory.get_object( Local( global_ctx.config.data ))
global_ctx.dataset = data_manager

2025-02-07 12:31:28,-533866475 | INFO | 3841452 - Creating Global Context for: configs/survey/IMDB.jsonc
2025-02-07 12:31:28,-533866406 | INFO | 3841452 - Setting seeds to: 0
2025-02-07 12:31:28,-533866368 | INFO | 3841452 - Caching System: True.


/NFSHOME/adangelo/miniconda3/envs/representer/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2025-02-07 12:31:30,-533864578 | INFO | 3841452 - Created Configurable: erasure.data.preprocessing.reshape_x_z.reshape_x_z
2025-02-07 12:31:36,-533857903 | INFO | 3841452 - Instantiating: erasure.data.preprocessing.tokenize_text.TokenizerWrapper
2025-02-07 12:31:37,-533857085 | INFO | 3841452 - Created Configurable: erasure.data.preprocessing.tokenize_text.TokenizeX
2025-02-07 12:31:37,-533857084 | INFO | 3841452 - Created Configurable: erasure.data.data_sources.HFDataSource.HFDataSource
2025-02-07 12:31:37,-533857083 | INFO | 3841452 - {'class': 'erasure.data.data_sources.HFDataSource.HFDataSource', 'parameters': {'path': 'fgiobergia/imdb-id', 'data_columns': ['text', 'movie_id'], 'label': 'score', 'to_encode': ['movie_id', 'score'], 'preprocess': [{'class': 'erasure.data.preprocessing.reshape_x_z.reshape_x_z', 'parameters': {'keep_as_x': [0], 'move_to_z': [1]}}, {'class': 'erasure.data.preprocessing.tokenize_text.TokenizeX', 'parameters': {'tokenizer': {'class': 'erasure.data.preproc

Map: 100%|██████████| 50000/50000 [00:04<00:00, 12373.02 examples/s]

2025-02-07 12:31:56,-533838087 | INFO | 3841452 - <torch.utils.data.dataset.ConcatDataset object at 0x7f391ab5d3d0>
2025-02-07 12:31:56,-533838086 | INFO | 3841452 - Instantiating: erasure.data.datasets.DataSplitter.DataSplitterPercentage
2025-02-07 12:31:56,-533838007 | INFO | 3841452 - ['all', 'all_shuffled', '-']
2025-02-07 12:31:56,-533838006 | INFO | 3841452 - Instantiating: erasure.data.datasets.DataSplitter.DataSplitterByZ



Filtering Data: 100%|██████████| 10/10 [02:38<00:00, 15.86s/it]

2025-02-07 12:34:35,-533679314 | INFO | 3841452 - ['all', 'all_shuffled', '-', 'forget', 'other_ids']
2025-02-07 12:34:35,-533679312 | INFO | 3841452 - Instantiating: erasure.data.datasets.DataSplitter.DataSplitterPercentage
2025-02-07 12:34:35,-533679309 | INFO | 3841452 - ['all', 'all_shuffled', '-', 'forget', 'other_ids', 'retain', 'test']
2025-02-07 12:34:35,-533679309 | INFO | 3841452 - Instantiating: erasure.data.datasets.DataSplitter.DataSplitterConcat
2025-02-07 12:34:35,-533679307 | INFO | 3841452 - ['all', 'all_shuffled', '-', 'forget', 'other_ids', 'retain', 'test', 'train']
2025-02-07 12:34:35,-533679306 | INFO | 3841452 - ['all', 'all_shuffled', '-', 'forget', 'other_ids', 'retain', 'test', 'train']
2025-02-07 12:34:35,-533679306 | INFO | 3841452 - Created Configurable: erasure.data.datasets.DatasetManager.DatasetManager


In [3]:
data_manager.n_classes

8

In [4]:
forget_loader, _ = data_manager.get_loader_for('forget')
len(forget_loader)

15

In [5]:
train_loader, _ = data_manager.get_loader_for('train')

2025-02-07 12:35:24,-533630140 | INFO | 3841452 - TRAINING WITH 80193 samples


In [6]:
forget = data_manager.partitions['forget']
len(forget)

966

In [7]:
from transformers import BertTokenizer

# Load the same tokenizer used for tokenization
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Iterate through your DataLoader
for X, y in train_loader:
    print(X)
    print(y)

tensor([[[ 101, 2023, 2003,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]],

        [[ 101, 2023, 2143,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]],

        [[ 101, 2387, 2023,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]],

        ...,

        [[ 101, 1045, 1005,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]],

        [[ 101, 2010, 9427,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]],

        [[ 101, 1045, 2074,  ...,    0,    0,    0],
         [   1,    1,    1,  ...,    0,    0,    0]]])
tensor([3, 5, 7, 8, 7, 8, 8, 4, 3, 8, 8, 0, 4, 8, 7, 1, 5, 7, 8, 8, 8, 7, 3, 1,
        2, 8, 4, 2, 8, 4, 7, 6, 4, 8, 6, 8, 2, 8, 1, 5, 8, 8, 7, 2, 2, 5, 6, 8,
        7, 1, 8, 8, 0, 8, 7, 8, 5, 4, 1, 8, 8, 8, 2, 8])
tensor([[[  101,  2023,  3185,  ...,     0,     0,     0],
         [    1,     1,     1,  ...,     0,     0,     0]],

 

KeyboardInterrupt: 

In [7]:
import matplotlib.pyplot as plt

# Parameters
num_images_to_display = 40
images_per_row = 4  # Number of images per row for a grid layout
images_displayed = 0

# Collect and display images
plt.figure(figsize=(15, 10))  # Set the figure size

for X, y in forget_loader:
    # Convert the batch to NumPy
    np_images = X.permute(0, 2, 3, 1).numpy()  # Change shape to (N, H, W, C)
    
    # Loop through images in the batch
    for img, label in zip(np_images, y):
        images_displayed += 1
        
        # Add subplot for each image
        plt.subplot(num_images_to_display // images_per_row, images_per_row, images_displayed)
        plt.imshow(img)  # Assuming the range is already suitable for visualization
        plt.title(f"Label: {label.item()}")  # Display label
        plt.axis("off")
        
        if images_displayed == num_images_to_display:
            break  # Stop after displaying the required number of images
    if images_displayed == num_images_to_display:
        break

plt.tight_layout()  # Adjust spacing between subplots
plt.savefig('2820_new_new.png')
plt.show()


RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 4

<Figure size 1500x1000 with 0 Axes>

In [11]:
loader, _ = data_manager.get_loader_for('train')

2025-01-31 17:09:43,-1121971173 | INFO | 346018 - TRAINING WITH 124594 samples


In [ ]:

from erasure.utils.config.global_ctx import bcolors


#Create Predictor
current = Local(global_ctx.config.predictor)
current.dataset = data_manager
predictor = global_ctx.factory.get_object(current)
global_ctx.predictor = predictor
global_ctx.logger.info('Global Predictor: ' + str(predictor))

#Create unlearners 
unlearners = []
unlearners_cfg = global_ctx.config.unlearners
for un in unlearners_cfg:
    current = Local(un)
    current.dataset = data_manager
    current.predictor = copy.deepcopy(predictor)
    unlearners.append( global_ctx.factory.get_object(current) )


#Evaluator
current = Local(global_ctx.config.evaluator)
current.unlearners = unlearners
evaluator = global_ctx.factory.get_object(current)

# Evaluations
for unlearner in unlearners:
    global_ctx.logger.info(f'''{bcolors.OKGREEN}####\t\t Evaluating: {unlearner.__class__.__name__} \t\t####{bcolors.ENDC}''')
    evaluator.evaluate(unlearner,predictor)

2025-02-06 23:09:49,-581965562 | INFO | 3533630 - Instantiating: erasure.model.classifiers.BERT_classifier.BERTClassifier


2025-02-06 23:09:50,-581964306 | INFO | 3533630 - Instantiating: torch.optim.AdamW
2025-02-06 23:09:50,-581964301 | INFO | 3533630 - Instantiating: torch.nn.CrossEntropyLoss
2025-02-06 23:09:50,-581964278 | INFO | 3533630 - TRAINING WITH 102142 samples
